### ISSUE TITLE
Animal Bestie Game: Media Queries missing

### ISSUE THREAD

**Issue by tati-guzman** [tati-guzman/techtonica-assignments#20]
## Summary of Issue

In the [Animal Besties Game](https://github.com/tati-guzman/techtonica-assignments/tree/main/game) there are no media queries present. Thus, game is not responsiveness to display size.

### Where was the problem found?

[Style CSS File](https://github.com/tati-guzman/techtonica-assignments/blob/main/game/style.css)

### Type of Problem

Styling: This is a CSS issue.

### Suggested Solution

Add media queries to account for mobile and tablet displays. With each smaller screen, the pictures don't have to be side by side. They can also decrease in size as the screen gets smaller. Margins/padding may have to be updated as well.

**Comment by jsnorek** [comment]
I can tackle this one!

**Comment by tati-guzman** [comment]
Thank you! Just assigned it to you!

**Comment by tati-guzman** [comment]
Resolved via PR #24 - thank you!
