### ISSUE TITLE
Connections React Game: Media Queries missing

### ISSUE THREAD

**Issue by tati-guzman** [tati-guzman/techtonica-assignments#21]
## Summary of Issue

In the [Connections React Game](https://github.com/tati-guzman/techtonica-assignments/tree/main/react-game/reactgame) there are no media queries present. Thus, game is not responsiveness to display size.

### Where was the problem found?

[App CSS file](https://github.com/tati-guzman/techtonica-assignments/blob/main/react-game/reactgame/src/App.css)

### Type of Problem

Styling: This is a CSS issue.

### Suggested Solution

Add media queries to account for mobile and tablet displays. With each smaller screen, margin/padding can be updated. Button location and size should also be adjusted appropriately.

**Comment by stmcpeters** [comment]
hey Tati! i'd love to work on this for you :)

**Comment by tati-guzman** [comment]
Thank you! Just assigned it to you!

**Comment by tati-guzman** [comment]
Issue addressed in PR #22 - changes have been merged!
