### ISSUE TITLE
Hover effect is not working on buttons - need to update via state

### ISSUE THREAD

**Issue by tati-guzman** [tati-guzman/techtonica-assignments#7]
### Summary of Issue

In the React Game, the button hover is not working. The button colors are a state that is updated based on the buttons being selected or matched. If we make the button hover settings override everything with "!important" it makes all the buttons have a hover even when they are disabled.

The goal is for the buttons to have a hover effect only when they have not been matched. Ideally, the submit button will have a different color for its hover than the word buttons.

### Where was the problem found?

[CSS file for React App: Lines 17-20 are the attempt at the hover](https://github.com/tati-guzman/techtonica-assignments/blob/main/react-game/reactgame/src/App.css#L17-L20)

### Type of Problem

Syntax error: The hover is not being set correctly.

### Suggested Solution

Update the [Word component](https://github.com/tati-guzman/techtonica-assignments/blob/main/react-game/reactgame/src/Word.jsx) to have logic that will trigger a button hover if the matched state is not set for that word.

**Comment by abbiehuynh** [comment]
Hi Tati, I would love to work on this issue. Could you please assign it to me?

**Comment by tati-guzman** [comment]
Hi Abbie, definitely! Thank you!

**Comment by abbiehuynh** [comment]
Resolved with commits: 3cd98e1 .

**Comment by tati-guzman** [comment]
Issued resolved via PR #23 - thanks again!
